steps:
  # Grab the latest version, store in workspace
  - id: "Read New Version Number from npm"
    name: "node"
    entrypoint: "sh"
    args: ["-c", "npm view firebase-tools version > /workspace/version_number.txt"]
  # Publish the Firebase docker image
  # Publish the Firebase docker image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "docker build -t gcr.io/$PROJECT_ID/firebase:$(cat /workspace/version_number.txt) -t gcr.io/$PROJECT_ID/firebase:latest -f ./Dockerfile ."

images:
  - "gcr.io/$PROJECT_ID/firebase"
