name: Web Frameworks tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - "**"
  release:
    types:
      - published
  schedule:
    - cron: 0 0 * * 1-5

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node: [ "16", "18" ]
        # dropping "nuxt", "nuxt3" for now
        framework: [ "next", "angular", "custom", "vite" ]
      fail-fast: false
    name: Test ${{ matrix.framework }} on Node ${{ matrix.node }} (${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - name: node_modules cache
        id: node_modules_cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-
      - name: Install deps
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Firebase emulator cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: firebase_emulators
      - name: Test
        run: |
          node lib/bin/firebase.js experiments:enable webframeworks
          node --loader ts-node/esm ./scripts/frameworks-tests/test-${{ matrix.framework }}.ts
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
